name: DANUWA-MD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Start Bot
        run: node index.js
        env:
          SESSION_ID: ${{ secrets.SESSION_ID }}
          PORT: 8000
